### ISSUE TITLE
Usage with Grafana 7

### ISSUE THREAD

**Issue by winestein** [flant/grafana-statusmap#102]
Hey, everyone! First of all, thanks for the plugin.

I would like to know if the plugin is compatible with Grafana version 7, and case it isn't, if there's a plan to make so. 

I'm currently able to use it with Grafana version 6.6.2. But when using version 7, with a subset of the example provided in the [k8s example](https://github.com/flant/grafana-statusmap/blob/master/example/k8s/dashboard.json), I couldn't make it work. The metrics and the legend are shown, but the buckets are not.

Thanks in advance!

**Comment by diafour** [comment]
Hello! The issue with 6.7 and 7.0 is fixed in the master branch.  See also #98. No release to the Grafana repository yet.

**Comment by winestein** [comment]
Thanks a lot for the quick response, @diafour. Everything is working perfectly using the lastest release from the repo!
