### ISSUE TITLE
Doesn't render with grafana 6.7.2, 6.7.4

### ISSUE THREAD

**Issue by mad-ady** [flant/grafana-statusmap#104]
Hello,

Great job on the plugin! I've used it with Grafana 6.2.4 but now upgrade to the latest 6.x grafana. However, the graphs no longer rendered, though the query did return data.
I tested with:
```
grafana/grafana       6.7.4               be4c69a1aae8        27 hours ago        233MB
grafana/grafana       6.7.2               322e0a666176        2 months ago        233MB
```
Haven't tested with 7.x yet, but reverted to 6.6.2 and it works correctly
I'm running version 0.2.0 of the plugin.

**Comment by diafour** [comment]
It is fixed in this repo, but not released to the plugin repository yet. https://github.com/flant/grafana-statusmap/issues/102
