### ISSUE TITLE
Unexpected color of gradient in 0.3.2

### ISSUE THREAD

**Issue by alxrem** [flant/grafana-statusmap#124]
statusmap v0.3.2 (according to plugins page in grafana)
grafana Grafana v7.1.1 (3039f9c3bd)

Metric has values from 0 to 1. At the time of observation the metric value is 1. But statuses are displayed with a gradient color corresponding to a value of 0.

![statusmap-bug-0 3 2](https://user-images.githubusercontent.com/123157/90683782-c904be80-e26f-11ea-9e8f-638d9dfd9dca.png)

Here is the same values displayed by statusmap v0.2.0:

![statusmap-0 2 0](https://user-images.githubusercontent.com/123157/90683828-d6ba4400-e26f-11ea-815e-308653e8b8c6.png)

**Comment by lekspyl** [comment]
Can confirm, 0.3.2 on Grafana 7.0.1.

**Comment by lekspyl** [comment]
This behavior is inconsistent: if dataset contains metric values with 0s (red) and 1s (green) colors render correctly:
<img width="1022" alt="Screenshot 2020-08-20 at 19 13 20" src="https://user-images.githubusercontent.com/31690776/90797592-7ed81780-e319-11ea-87bc-4a109991356b.png">
but if there are only 1s then we observe the same behavior @alxrem described:
<img width="1024" alt="Screenshot 2020-08-20 at 19 12 54" src="https://user-images.githubusercontent.com/31690776/90797690-a62ee480-e319-11ea-8109-dace18647e5e.png">

**Comment by diafour** [comment]
Thank you for your reports. It is definitely a bug and should be fixed.
