### ISSUE TITLE
Pagination controls don't work

### ISSUE THREAD

**Issue by recapp-developer** [flant/grafana-statusmap#125]
Hi,

I have enabled pagination. In the panel editor view (in version 7.1 of grafana) the pagination works as expected. But when I apply and toggle back to the main dashboard view the pagination doesn't work.

Any ideas why?

Thanks,
Mike

**Comment by diafour** [comment]
Hello! Can you upload screenshots of an editor view and the main dashboard? Also, which datasource do you use?
