### ISSUE TITLE
Dashboard doesn't resolve below 15s interval

### ISSUE THREAD

**Issue by Jeff-L-Tsai** [flant/grafana-statusmap#127]
Hi there,

We have a low scrape interval (1s) Prometheus for the purpose of performance tuning. We noticed that the statusmap panel doesn't resolve metric points below 15s interval. 

I was wondering if I'm missing something or this is in the works?

![image](https://user-images.githubusercontent.com/56048511/91208102-87847100-e6be-11ea-9f1d-d5598ce69229.png)

Thanks,
Jeff

**Comment by diafour** [comment]
Hi!

Did you set "Scrape interval" in a datasource options? It is 15s by default for the Prometheus datasource. "Min time interval" is not an override of this option.

**Comment by Jeff-L-Tsai** [comment]
Hi,

I think the scrape interval is set to 1s, because our other panels were able to display second by second metrics when I set the "Min time interval" to 1s. 
![image](https://user-images.githubusercontent.com/56048511/91229752-35a01300-e6df-11ea-8d7e-0cfe3e2ac70f.png)
![image](https://user-images.githubusercontent.com/56048511/91230127-d42c7400-e6df-11ea-975e-1c1f3be68ca8.png)

**Comment by diafour** [comment]
So, I have success with 1s resolution in Grafana 6.7.3 and 7.1.4. What is your exact version? (There were changes between 6.x versions that broke interval adjusting, may be that is the case).

<img width="1087" alt="Снимок экрана 2020-08-26 в 12 56 49" src="https://user-images.githubusercontent.com/1055474/91289908-9ee55c00-e79b-11ea-9f5d-73fd06bfac10.png">

**Comment by Jeff-L-Tsai** [comment]
You were right about the interval... I double checked and noticed that we didn't have it specified. Statusmap was able to render per second metrics after adding the jsonData: timeInterval in datasource yaml. I wonder why the other native Grafana dashboards didn't have this issue...

We are using Granafa 6.7.3 and Statusmap 0.2.0 for reference. 

Love your plugin and thanks for the help!
