### ISSUE TITLE
I can't add 2+ instances of statusmap on the same dashboard

### ISSUE THREAD

**Issue by imilyukov** [flant/grafana-statusmap#129]
When I try to add 3 or more statusmap widgets on the same dashboard page I have an error "property name doesn't read from NULL object" and widget doesn't display

The problem is on the line:
https://github.com/flant/grafana-statusmap/blob/master/src/module.ts#L153

You should avoid to change global variable in the module:
https://github.com/flant/grafana-statusmap/blob/master/src/module.ts#L66

**Comment by diafour** [comment]
Hi! Nice catch! It is a (not working) workaround for old versions of Grafana. What version do you use?

**Comment by imilyukov** [comment]
Hi @diafour,

I have upgraded the plugin to v0.3.1. 
I have 5 statusmap widgets on a dashboard, after upgrade by new version I have seen only 2

**Comment by diafour** [comment]
What version of Grafana do you use? There are no problems with Grafana 6.7+.

**Comment by diafour** [comment]
Fixed it. Can you update the plugin from the master branch?

**Comment by imilyukov** [comment]
I use grafana of version 6.3.5. 

Did you already fix it? Great! When are you planning to make a new release with this fix?

Many thanks
