### ISSUE TITLE
Unsigned plugin notification - Grafana 7.1.5

### ISSUE THREAD

**Issue by chelnak** [flant/grafana-statusmap#131]
After installing this plugin in Grafana 7.1.5 it's displayed as Unsigned and doesn't show up in the list of available visualisations.

Are there any plans to sign the statusmap plugin?

Ref: https://grafana.com/docs/grafana/latest/plugins/plugin-signature-verification/

As a workaround I have added the following to grafana.ini, however this might not be acceptable in some environments:
```
[plugins]
allow_loading_unsigned_plugins = flant-statusmap-panel
```

**Comment by diafour** [comment]
Hello!

What I know about signing:

1. Grafana has no process to sign third-party plugins:
https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/
https://community.grafana.com/t/how-to-create-a-signed-backend-plugin/30068

2. `allow_loading_unsigned_plugins` is an option to allow backend plugin loading, plugin still be displayed as "Unsigned".
https://github.com/grafana/grafana/issues/26123

3. Panel plugins should work without signing and without allow_loading_unsigned_plugins. 

So, can you share grafana logs, "Plugins" page screenshot and a "New dashboard" page screenshot?

p.s. Classic "It works for me":
<img width="1280" alt="Снимок экрана 2020-09-11 в 21 20 53" src="https://user-images.githubusercontent.com/1055474/92960713-c401ec00-f476-11ea-817c-d79f351a69df.png">
<img width="760" alt="Снимок экрана 2020-09-11 в 21 23 35" src="https://user-images.githubusercontent.com/1055474/92960733-cb28fa00-f476-11ea-85d1-b14720af8449.png">

**Comment by diafour** [comment]
There is progress in the signing process from Grafana team.  The steps to implement plugin signing:

- [x] ~Acquire an organization account on grafana.com and get API key.~
- [ ] Make plugin compatible with grafana-toolkit.
- [ ] Create Github Actions workflow that (1) build plugin, (2) archive dist directory, (3) sign it and (4) upload archive as an asset.
- [ ] Publish first signed release.

**Comment by diafour** [comment]
v0.4.0 is the first signed release. I think this issue can be closed now.
