### ISSUE TITLE
Metrics without "status" label

### ISSUE THREAD

**Issue by AlbMor** [flant/grafana-statusmap#136]
Hi

I am trying to use this plugin but my metric does not have "status" label.

Instead we have combined status based on two labels (metric is form Prometheus)

e.g.
metric is  azure_devops_agentpool_agent_info
it has two labels 
enabled="true" or "false"
status="online" of "offline"

I need to have the combined two labels as

enabled      |     status       |        STATUS FOR PLUGIN
------------ | ------------- | -------------
 true           |      online           |             1
 false          |      online           |             2
 true          |       offline          |              3
 false           |     offline          |              4

each of the combination should have a number associated  as STATUS FOR PLUGIN that has to be used for the this plugin

Can you help to figure out how to set it up since I don´t have a overall "status" label but a combination of two?

Thanks

Alberto

**Comment by diafour** [comment]
Hello! You can use two labels to filter possible states:

```
Query A
(max_over_time(some_metric{enabled="true", "status="online"}[$__interval]) == 1) * 1

Query B
(max_over_time(some_metric{enabled="false", "status="online"}[$__interval]) == 1) * 2

Query C
(max_over_time(some_metric{enabled="true", "status="offline"}[$__interval]) == 1) * 3

Query D
(max_over_time(some_metric{enabled="false", "status="offline"}[$__interval]) == 1) * 4
```

**Comment by AlbMor** [comment]
Hi @diafour 

Thanks for the info.

I have already filtered out the 4 combinations as you described.

What I am missing is how to use those values within the status map.

Can you help me with it?

Thanks

Alberto

**Comment by diafour** [comment]
The next steps are in README: https://github.com/flant/grafana-statusmap#panel

1. Setup y-axis labels by filling "legend" fields of each query with something like "{{status}} enabled={{enabled}}" or may be something more meaningful.

2. Choose 'Discrete' mode in visualization options.

3. Setup color for each numeric value: 1, 2, 3, 4.

**Comment by AlbMor** [comment]
@diafour 

Thanks so much

I was able to set it up

Thanks

Alberto
