### ISSUE TITLE
Way to use with Elastic search datasource

### ISSUE THREAD

**Issue by yongicobay** [flant/grafana-statusmap#166]
Hello,

statusmap seems to be the panel i've been searching for a while, but i can't get it to work with my elastic search datasource.
This one contains records with the following fields (among others) : timestamp, project, issue, phase, assignee.
Project , issue and phase are fixed in my lucene query (for example project:52 AND  issue:246 AND phase:Doing), and i want to display assignees change for the specified phase. 
I used transformation to filter fields and only keep timestamp and assignee, but still it doesn't work.

Any idea of what i have done wrong ?

Thank you

**Comment by yongicobay** [comment]
As i've noticed that all my phases weren't of the same duration, this won't in fact fit my need.

**Comment by diafour** [comment]
Transformations are not supported right now: #150.
