### ISSUE TITLE
Grafana 7.4.x support.

### ISSUE THREAD

**Issue by hawran** [flant/grafana-statusmap#169]
After upgrade to grafana `7.4.0` the legend is the only thing rendered.
(same as https://github.com/flant/grafana-statusmap/issues/135?)

Plugin: `Version 0.3.4`

**Comment by diafour** [comment]
New version, new challenges... Thanks for the report.

**Comment by hawran** [comment]
> New version, new challenges... Thanks for the report.

:-)
You're welcome.

**Comment by zameeransari** [comment]
Upgraded our Grafana instance from 6.7.2 to 7.3.6, all our dashboards which are using statusmap plugin went blank. 0.3.4 version is installed, also tried immediate previous 0.3.2 but didn't worked. Now migrating dashboards to heatmap. No idea why it is not working, is it known compatibility issue?

**Comment by waardd** [comment]
Same problem here with Grafana v7.4.1

**Comment by waardd** [comment]
Is this issue now closed or not?
Is there a solution?
