### ISSUE TITLE
Request: add clickable cells / drill-down support

### ISSUE THREAD

**Issue by edum18** [flant/grafana-statusmap#17]
It would be amazing if we could click the cells and redirect to any URL, basically support drill-down.
Use case: I have some cells with different colors and would like to see more details about a red cell.
Are there any plans to include this?
Thanks for the plugin.

**Comment by diafour** [comment]
Great feature! Do you have some examples of clickable cells in other panel plugins? May be ready to use dashboard? Have no idea what options to define for mvp ;)

**Comment by edum18** [comment]
I didn't find any other panel plugin with that feature.
As a work-around I managed to have what I want adding some code, like setting a new `window.location.href` on your `function onMouseDown(event)` of a cell. I added an input box to the options menu to set the new URL I want for each panel too. Also, on the full new URL, I added X and Y values of the selected cell so I can get them on the new redirected dashboard.

**Comment by kvolkovich-sc** [comment]
Also it would be cool to have clickable Y axis items.

**Comment by RafaelSnor** [comment]
it could be freat if you add support for mysql datasource

**Comment by binduv124** [comment]
Is this feature clickable cells / drill-down available?

**Comment by szhem** [comment]
@edum18 could you be so kind to create a pull request for your changes?

**Comment by diafour** [comment]
I think there might be a separate tab called for example 'URLs' where you can define url templates for y-axis items, cells and for tooltip items. Templating investigation is also required for #41.

**Comment by CameronSinclair84** [comment]
Hey all, what is the latest update with regards to clickable cells / drill down? Is there a straightforward way for me to add this functionality to my panel? Thanks in advance!

**Comment by diafour** [comment]
@CameronSinclair84 a frozen tooltip is implemented to address this issue.
