### ISSUE TITLE
Some sections in the settings menu utilize different font

### ISSUE THREAD

**Issue by nabokihms** [flant/grafana-statusmap#170]
MacOS BigSur 11.1
Google Chrome 88.0.4324.96
Grafana 7.0.6

Screen shot:
<img height="265" alt="image" src="https://user-images.githubusercontent.com/32434187/107206412-70410200-6a18-11eb-879d-a29ef1992049.png">

**Comment by diafour** [comment]
@nabokihms the screenshot is for Statusmap v0.3.0 (yes, we still use it). That version has an outdated layout in options_editor.html and the problem was fixed in #118.
