### ISSUE TITLE
Sign Plugin for Grafana Cloud Support

### ISSUE THREAD

**Issue by mumblez** [flant/grafana-statusmap#171]
Hi,

Grafana Cloud (managed Grafana) will now only allow signed plugins, the service has currently marked this plugin as 'Unsigned'.

Any chance this will get signed any time soon?

We love your plugin and use it in numerous dashboards!

[How to sign](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)
[Signing Info](https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/)

Many Thanks

**Comment by diafour** [comment]
Hello! Here is a link to a related issue: https://github.com/flant/grafana-statusmap/issues/131#issuecomment-735740854
Signing is also mandatory to publish plugin releases, so the next release (0.4.0) will be signed. There is a critical issue with Grafana 7.4 #169 and we do our best to release 0.4.0 ASAP.

**Comment by mumblez** [comment]
thanks @diafour , look forward to to the next release.
I'll close this.
