### ISSUE TITLE
Publish version 0.4.1 in Grafana plugin repository

### ISSUE THREAD

**Issue by diafour** [flant/grafana-statusmap#183]
A new release is ready: https://github.com/flant/grafana-statusmap/releases/tag/v0.4.1

PR is opened to publish the new version on Grafana.com: grafana/grafana-plugin-repository#874

Wait for approval... 🤞

**Comment by hawran** [comment]
Sorry for my impatience but I can see
```
  "links": [
    {
      "rel": "self",
      "href": "/plugins/flant-statusmap-panel"
    },
    {
      "rel": "versions",
      "href": "/plugins/flant-statusmap-panel/versions"
    },
    {
      "rel": "latest",
      "href": "/plugins/flant-statusmap-panel/versions/0.3.4"
    },
    {
      "rel": "download",
      "href": "/plugins/flant-statusmap-panel/versions/0.3.4/download"
    }
  ]
```
at https://grafana.com/api/plugins/flant-statusmap-panel.
(I might be too hasty, of course)

**Comment by shurup** [comment]
@hawran it takes some time for Grafana plugins repo maintainers to approve our request (check the PR above) — we can't do anything with that. Sometimes it could be even a week or two. But we hope for the best :-)

**Comment by hawran** [comment]
> @hawran it takes some time for Grafana plugins repo maintainers to approve our request (check the PR above) — we can't do anything with that. Sometimes it could be even a week or two. But we hope for the best :-)

Oh, I see.
So :fingers_crossed: then

**Comment by diafour** [comment]
0.4.1 is published!

**Comment by maxisam** [comment]
This doesn't work with 7.5.2

**Comment by shurup** [comment]
@maxisam hello! Please create a separate issue with details (what exactly happens when you try the statusmap with your installation). Thanks!
