### ISSUE TITLE
Data has value with undefined color - Grafana 7.4.1

### ISSUE THREAD

**Issue by bkiziuk** [flant/grafana-statusmap#184]
**What happened**:

The UI graph claims that values that should be displayed are not defined in color mapping even if they are. See screenshot.
I'm using numerical values which have been working just fine with Statusmap 0.3.0 and previous Grafana versions.
Black bars are displayed instead of defined color.
The screenshot includes a redundant value in purple color which has been added for testing only. It did not change the result.

**What you expected to happen**:

The value should be recognised if it is defined.

**How to reproduce it (as minimally and precisely as possible)**:

Have some discreet numerical values provided from Influx data-source.
I'm not able to test with text values, but Data Inspector shows that values returned from data-source are fine.

**Environment**:
- Grafana version: Grafana v7.4.1 (07649d1313)
- flant-statusmap-panel version: 0.4.0 (Release)
- Data source type & version: InfluxDB Version: 1.8.4-1
- OS Grafana is installed on: Debian Buster
- User OS & Browser: Windows 7 Prof, Opera 74.0.3911.107
- Grafana plugins: built-in only + statusmap
- Others:

**Anything else we should know?**:

![flant-statusmap_0-4-0](https://user-images.githubusercontent.com/32905985/108319658-04059180-71c2-11eb-8c9b-ebfa89bef7da.png)

**Comment by diafour** [comment]
Hello! Thank you for this bug report. The bug is reproducible with TestdataDb and Prometheus datasources. I'll fix it ASAP and cut a new release.

**Comment by diafour** [comment]
The fix is released. https://github.com/flant/grafana-statusmap/releases/tag/v0.4.1

**Comment by bkiziuk** [comment]
Fix confirmed. Many thanks for lightning response :-)
