### ISSUE TITLE
Grafana 7.4.5 support

### ISSUE THREAD

**Issue by whitingjr** [flant/grafana-statusmap#206]
I know the version is very specific. Support for 7.4.x was addressed in #135 but something may have broken since then.

**What happened**:
Missing Statusmap from Panel visualization

**What you expected to happen**:
To see Statusmap as an option

**How to reproduce it (as minimally and precisely as possible)**:
install statusmap plugin using grafana-cli
Create a new Dashboard, add a new Panel
click on Visualizations

**Environment**:
- Grafana version: 7.4.5
- flant-statusmap-panel version: 0.4.1
- Data source type & version: Redis
- OS Grafana is installed on: Container default: 
- User OS & Browser: Firefox 88.0.1
- Grafana plugins: flant-statusmap-panel, simpod-json-datasource, performancecopilot-pcp-app

**Anything else we should know?**:
The newly installed Statusmap panel is listed as expected in the Plugins list.

**Comment by whitingjr** [comment]
Oh and the logs do not report any err messages.

**Comment by diafour** [comment]
Hello! Grafana loads plugin at startup, so you need to restart the server after installing new plugins.

I've run `grafana-cli plugins install flant-statusmap-panel` inside docker `grafana/grafana:7.4.5` and it works as expected after restart.

**Comment by whitingjr** [comment]
Did you see the option to select the panel type ?

**Comment by whitingjr** [comment]
There must be something wrong with my Jenkins set-up. Closing this issue.
