### ISSUE TITLE
Annotation Query Failed Cannot read property 'to' of undefined

### ISSUE THREAD

**Issue by Sinketsu** [flant/grafana-statusmap#219]
**What happened**:
When dashboard refresh, an error occurs. 
`Annotation Query Failed`
`Cannot read property 'to' of undefined`

In console:
>AnnotationSrv.query error TypeError: Cannot read property 'to' of undefined
    at Module.j (rangeutil.ts:269)
    at y (annotations_srv.ts:236)
    at annotations_srv.ts:157
    at async Promise.all (/d/RHTucjGnz/index 0)
    at async Promise.all (/d/RHTucjGnz/index 0)

And the annotations are not drawn.

**What you expected to happen**:

Draw annotations on a panel.

**How to reproduce it (as minimally and precisely as possible)**:

Install `Grafana v8.1.1 (90c87a52f7)` with `flant-statusmap-panel 0.4.1`

**Environment**:
- Grafana version: v8.1.1 (90c87a52f7)
- flant-statusmap-panel version: 0.4.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Yandex browser 21.6.0.1108
- Grafana plugins:
- Others:

**Anything else we should know?**:
![image](https://user-images.githubusercontent.com/20300377/129195576-f1b61685-ff88-470f-9d1e-f48c48e4e5e5.png)

**Comment by danger89** [comment]
AnnotationSrv.query error TypeError: e is undefined
    j https://stats.melroy.org/public/build/app.843e85298b12060ea650.js:5798
    y https://stats.melroy.org/public/build/app.843e85298b12060ea650.js:4717
    getGlobalAnnotations https://stats.melroy.org/public/build/app.843e85298b12060ea650.js:4717
app.843e85298b12060ea650.js:4717:9600
    getAnnotations https://stats.melroy.org/public/build/app.843e85298b12060ea650.js:4717

**Comment by Cjkeenan** [comment]
It looks like there might be a related issue here, could go over there to chime in with any additional info:
https://github.com/grafana/grafana/issues/37819

**Comment by roastiek** [comment]
The range parameter is undefiened in 8.1.x when calling `getAnnotations` for the first time. But on the next call (refresh), the range has already a value.

Just added simple `console.log(this.range)` before `getAnnotations`.

https://github.com/flant/grafana-statusmap/blob/bc96037286df3d77333605c68c78f182fca976e2/src/module.ts#L336-L341

**Comment by roastiek** [comment]
I'm suspecting this commit https://github.com/grafana/grafana/commit/6f38883583c4c43af149f68db482b39a3240ec95.

The `updateTimeRange` is no longer called before `issueQueries` so `this.range` is not set until `super.issueQueries` is called.

Adding `this.updateTimeRange(datasource);` before using `this.range` fix this for me.

**Comment by danger89** [comment]
Looking forward for the fix anytime soon! 👍🏽

**Comment by KannappanSomu** [comment]
+1

**Comment by diafour** [comment]
I've merged a fix. Need to cut a release.

**Comment by danger89** [comment]
I can't wait 🍰
