### ISSUE TITLE
Display error when use zabbix datasource

### ISSUE THREAD

**Issue by tomcsi** [flant/grafana-statusmap#220]
If I use zabbix datasource, all works perfectly, but all of time refreshing the page then display the error dialog top right.

Error message: Cannot read property 'to' of undefined

**Environment**:
- Grafana version: 8.1.1
- flant-statusmap-panel version: 0.4.1
- Data source type & version: Zabbix 4.2.1
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: MacOS & Chrome latest

**Comment by headfox23** [comment]
With the last update of grafana to (Grafana v8.1.1 (a10d7f91d3) )we get exactly the same error message:
![image](https://user-images.githubusercontent.com/21370291/134315117-4369995f-92c0-43cb-8893-8cf972190cf1.png)

**Comment by diafour** [comment]
See #219
