### ISSUE TITLE
Cannot read properties of undefined (reading 'to') in Grafana v8.1.3 (a61f38238c)

### ISSUE THREAD

**Issue by stakeconomy** [flant/grafana-statusmap#221]
We are receiving an popup on Grafana version v8.1.3 (a61f38238c)
Probably not supported yet, I know. But are there plans to work on Grafana v8.* support for statusmap? 
We use this plugin a lot in our environment, and we like it a lot.

**Environment**:
- Grafana version: v8.1.3 (a61f38238c)
- flant-statusmap-panel version: v0.4.1
- Data source type & version: Prometheus

Any tips?

**Comment by stakeconomy** [comment]
Hi, anyone from @flant that can respond to my question? :)

**Comment by stakeconomy** [comment]
Fixed it myself

**Comment by shurup** [comment]
Hi @stakeconomy, would you mind sharing your fix here, please? The new Grafana version brought another change that we needed to consider (#219) but didn't have time for that yet. Was your fix similar to the one mentioned [here](https://github.com/flant/grafana-statusmap/issues/219#issuecomment-918136073)?
