### ISSUE TITLE
Value names mapping for bucket with "Multiple values"

### ISSUE THREAD

**Issue by kvolkovich-sc** [flant/grafana-statusmap#32]

**Comment by diafour** [comment]
@kvolkovich-sc Please provide more info. There is a tooltip with names of values for every bucket. Is it insufficient?

**Comment by diafour** [comment]
Looks like this issue is fixed in https://github.com/flant/grafana-statusmap/pull/34

**Comment by kvolkovich-sc** [comment]
My point is add possibility to give meaningful names to values:

```
value_1: 10
value_2: 30
```
=>

```
Warning incindents: 10
Critical incindents: 30
```

Something similar like you can remap "Column Header" at "Column styles" for Grafana's table panel.

**Comment by diafour** [comment]
There is a mapping in discrete mode. You can set tooltip for particular values:

![mapping](https://raw.githubusercontent.com/flant/grafana-statusmap/master/src/img/color-preset-02.png)

These tooltips are displayed on hover the cell. 

Please give more information: which metrics you define or a sample of your input values and target names, which mode you use, may be a screenshot of what panel is displayed now for your inputs, etc.

**Comment by diafour** [comment]
@kvolkovich-sc is this issue still affects you? BTW there is a request to add prometheus labels into tooltips — #41.

**Comment by kvolkovich-sc** [comment]
@diafour, I'll close it in favor of #41. It looks similar.
