### ISSUE TITLE
Request: display annotations

### ISSUE THREAD

**Issue by geku** [flant/grafana-statusmap#35]
We really like the statusmap panel to display various states over time but we miss the ability to display [Grafana annotations](http://docs.grafana.org/reference/annotations/), e.g. to visualize when deployments happened.

Many thanks for the plugin.

**Comment by diafour** [comment]
Great suggestion! I think this shouldn't be hard to implement.

**Comment by HenGold** [comment]
+1 here

**Comment by diafour** [comment]
Initial support is implemented in #56

**Comment by diafour** [comment]
Continue in #59
