### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by RestfulBlue** [flant/grafana-statusmap#61]
Hey boys, i am trying to use this beatiful plugin with my custom datasource, but i am getting this error :
TypeError : cannot read property 'then' of undefined,
status_heatmap_ctrl.js:211:60, function issueQueries. 
Is there a way to avoid that? all other plugins perfectrly working with this datasource :C Should i implement something in it? 
I am using grafana 5.3.0. Also i was tring to implement annotation methods in datasource and settting annotations to true in plugin.json of datasource, but that doesn't change anything :/

**Comment by diafour** [comment]
@RestfulBlue any updates? The code of `issueQueries` is from graph panel.

**Comment by RestfulBlue** [comment]
Hi! sorry for late response,
I was using windows 7 with one of the latest google chrome version(if its really matter i can supply it tomorrow). Datasource is working with any other panel. This code is really from native grafana panel, but loook like this block was added in 5.4.0 version.
For example, 5.3.4 doesn't have this block 
https://github.com/grafana/grafana/blob/v5.3.4/public/app/plugins/panel/graph/module.ts#L153
in 5.3.4 this block was looking like this : 
```
  issueQueries(datasource) {
    this.annotationsPromise = this.annotationsSrv.getAnnotations({
      dashboard: this.dashboard,
      panel: this.panel,
      range: this.range,
    });
    return super.issueQueries(datasource);
  }
```

Also 5.3.4 doesn't contain datasourcePromises in annotation_srv
https://github.com/grafana/grafana/blob/v5.3.4/public/app/features/annotations/annotations_srv.ts

**Comment by diafour** [comment]
Yep. I tested annotations in 5.4.3 and 6.0.0 only. Will check 5.3.x

**Comment by EricInBj** [comment]
same problem here, grafana 5.1.4 with influxdb datasource.

**Comment by diafour** [comment]
Fixed by #63. New version 0.1.1 is waiting for publishing https://github.com/grafana/grafana-plugin-repository/pull/406

**Comment by RestfulBlue** [comment]
@diafour everything works works fine now, thanks! <3

**Comment by diafour** [comment]
0.1.1 is published in grafana.net. Close this.
