### ISSUE TITLE
Different colors for legend format

### ISSUE THREAD

**Issue by makona18** [flant/grafana-statusmap#7]
Завезти возможность выбора цветов для legend format

**Comment by diafour** [comment]
Нужно больше деталей. В случае с discrete mapping цвета можно выбрать. Вопрос про opacity и gradient?

**Comment by makona18** [comment]
> Нужно больше деталей. В случае с discrete mapping цвета можно выбрать. Вопрос про opacity и gradient?

Вот допустим возьмём обычную таблицу, цвета графиков отображаются рядом с легендой
![untitled](https://user-images.githubusercontent.com/14859604/46922541-221bbf80-d013-11e8-9285-4aa4670c3c5d.png)
А при использовании statusmap названия легенд теряются, было бы круто добавить опцию, чтобы или текст сделать другого цвета или цветные метки, как у tables
![untitled2](https://user-images.githubusercontent.com/14859604/46922542-27790a00-d013-11e8-9295-2862d4e92fed.png)

**Comment by diafour** [comment]
Это эффект от dark темы. Если поправить #9, то проблемы не будет?

**Comment by diafour** [comment]
#9 поправлено, теперь выглядит так:
![Statusmap sample panel with dark theme](https://raw.githubusercontent.com/flant/grafana-statusmap/master/src/img/flant-statusmap-panel-dark.png)

**Comment by diafour** [comment]
Закрываю задачу, т.к. изменения по #9 теперь опубликованы как версия 0.0.2.

@makona18 если поддержки тёмной темы мало, то можно переоткрыть.
