### ISSUE TITLE
Auto-refresh does not repaint graph in IE

### ISSUE THREAD

**Issue by shep89** [flant/grafana-statusmap#73]
Hello.
After upgrading to grafana 6.2.3 graph stopped updating on autorefresh. Tested on versions of panel versions 0.0.3 and 0.1.1.
![image](https://user-images.githubusercontent.com/12829965/59662444-9e276200-91b5-11e9-8fb1-f4ac2455f249.png)

**Comment by diafour** [comment]
Does IE repaint graph if you click on the 🔄Refresh button?

**Comment by shep89** [comment]
Yes after page refresh graph is fully painted and after just moving left with no new data. Describing the screenshot above: refresh was pressed at 10:32 than i just waited to simulate this situation.

**Comment by shurup** [comment]
Looks like an old bug. Please feel free to reopen it if that's still relevant.
