### ISSUE TITLE
Tooltip displaying incorrect information

### ISSUE THREAD

**Issue by Dom4LM** [flant/grafana-statusmap#74]
The tooltip sometimes does not display the correct value for series name. For example, the status map below just shows count of data per hour from a table for three separate series (V002, V006 and V009). The tooltip displays "V009" for data from V006:

![image](https://user-images.githubusercontent.com/49551910/61285213-67466b00-a7b8-11e9-96f2-65c28d0cb8bd.png)

For some of the V009 series, no tooltip is displayed at all:

![image](https://user-images.githubusercontent.com/49551910/61285403-cb692f00-a7b8-11e9-996a-91507c9d9981.png)

Statusmap version: 0.1.1
Grafana version: 6.2.0
Data source: Clickhouse
Query:
![image](https://user-images.githubusercontent.com/49551910/61285550-11be8e00-a7b9-11e9-97b7-c61992c26609.png)

**Comment by CockatooV1** [comment]
I also have this Issue. It seems like there's an array of information that gets shifted when moving to a new row that's in view.
I have found it to usually occur when there are multiple rows of information with some null buckets of data. As I highlight a bucket on each row it gets progressively worse - the tool-tip that displays is actually for another bucket several away and with each row this distance increases.
When the tool-tip doesn't appear the shift seems to align with null values.

**Comment by humarf** [comment]
I faced this problem too. You should check the generated SQL with a database client to see the output. In my case timefilter macro together with rounding to full hour values (div 3600 * 3600) caused a problem that needed fixing. I went over last 24h with one bucket per hour but the query returned 25 buckets. When this happens tooltip goes crazy.

**Comment by mtncodes** [comment]
+1
Our tooltip data is often off by both row and time designation.

**Comment by diafour** [comment]
It is fixed with a new tooltip code. The fix is in master and will be in a 0.3.0 release.
