### ISSUE TITLE
v0.2.0 break when using Grafana 6.3.x

### ISSUE THREAD

**Issue by greut** [flant/grafana-statusmap#85]
When running the latest _published_ version of this plugin with any 6.3+ version of Grafana, it breaks during the edition of any dashboard. Going back to 6.2.x works still. What am I missing?

![statuspanel-bug](https://user-images.githubusercontent.com/1388/72724768-84536080-3b84-11ea-9f8a-01fd517fa62c.png)

**Comment by diafour** [comment]
Hello! Thank you for this report, I'll try to reproduce this behavior. What type of a datasource do you use?

**Comment by greut** [comment]
A Prometheus one which is fed by InfluxDB (configured as read/write)

**Comment by diafour** [comment]
@greut is this still relevant? I can't reproduce this problem with grafana 6.3.7.

I did some investigation, there was a change in 6.3 related to `dataFormats` option: https://github.com/grafana/grafana/pull/16984. This option is used to hide the query editor. The 'statusmap' plugin relates on query editor and doesn't use any of these options. It seems the problem with another plugin that hides the query editor.

**Comment by greut** [comment]
@diafour I'll run some upgrade and check that query editor setting. Many thanks for your time!
