### ISSUE TITLE
Use Rest API as datasource

### ISSUE THREAD

**Issue by J0nathan-S** [flant/grafana-statusmap#88]
Hello,

Id like to implement this status map with a custom data source (API with JSON Response). Unfortunately, I wasn't able to find, how the payload must be looking, in order to display data in this panel. 

Id appreciate, if you could write a little documentation about how the response exactly needs to look like.

Thanks in advance!

Jonathan S.

**Comment by diafour** [comment]
Hello. A custom data source is out of the scope of this plugin. There is related documentation in Grafana itself: https://grafana.com/docs/grafana/latest/plugins/developing/datasources/

**Comment by J0nathan-S** [comment]
Thank you. I Thought the data has to have a specific format.
