### ISSUE TITLE
Extratooltip not working after changing from cardsData to buckets

### ISSUE THREAD

**Issue by JoaquinJimenezGarcia** [flant/grafana-statusmap#92]
Hi @diafour !

I was rebasing your new changes in the plugin with our new funcionality about paginating elements when I realized that hasn't been changed the tooltipextraseries.ts  file, generating an error when a mouse click is done in one value

![Selection_001](https://user-images.githubusercontent.com/10835286/76949692-3e5b1480-6909-11ea-93ca-2f52bd9f926d.png)

Do you think you could fix it, please?

Thank you very much in advance.

**Comment by timberjoegithub** [comment]
I am stuck on this as well.

**Comment by JoaquinJimenezGarcia** [comment]
Hi @timberjoegithub ! I already fixed it.

I will make a new PR between today and tomorrow with this and another new feature.

**Comment by Matkill** [comment]
Hello, i have the same issue when i add an url on the status map
![image](https://user-images.githubusercontent.com/16704641/83271159-be371200-a1c9-11ea-935a-fecef0b629e4.png)

the extratooltip does not show the link
![image](https://user-images.githubusercontent.com/16704641/83271263-e4f54880-a1c9-11ea-8f2a-e9fc7b9d3c7e.png)

and i have this error in the console when i click on the green status

![image](https://user-images.githubusercontent.com/16704641/83271301-f5a5be80-a1c9-11ea-95ef-8d4cac10bf47.png)

How can i solve this ? I already re-cloned the repo to get the latest version.

Thanks for your work and your help on that !

**Comment by diafour** [comment]
@Matkill tooltip is reworked in #109, please try master branch.
