### ISSUE TITLE
Ignoring parameter "minimum interval" and "Min width for 1/1".

### ISSUE THREAD

**Issue by larspk** [flant/grafana-statusmap#94]
Grafana v6.7.2 (423a25fc32)
Plugin Statusmap. Version 0.2.0

After Grafana has been updated there are some problem with statusmap panel.
Parameters "minimum interval" and "Min width for 1/1" are being ignored.

For example, I set  "minimum interval"=2m but we have 30s interval beetwen cards. Earlier it worked.

Also, when we go back from the panel to dashboard, an error is showing "Cannot read property 'slice' of undefined". Maybe it's related.
<img width="412" alt="Screenshot 2020-04-14 at 15 21 20" src="https://user-images.githubusercontent.com/48494592/79226047-638a6680-7e66-11ea-8d26-99ab98283ac7.png">

**Comment by diafour** [comment]
Hi! There are some changes in Grafana 6.7 related to interval calculation. I think I fix this issue in #98 . Can you try it from master branch?
