### ISSUE TITLE
Unable to change opacity color

### ISSUE THREAD

**Issue by svdasein** [flant/grafana-statusmap#95]
When using the opacity mapping option,  it seems it's impossible to actually change the color.  The selector pops up, but when one tries to actually select something nothing happens and color stays the default green.

Browsers (linux platform 64bit):
Firefox 65.0.1
Chrome 73.0.3683.75

TypeError: "this is null"
	onCardColorChange module.ts:345
	n ng_react.ts:65
eval2Angular	eval
	apply
	n ng_react.ts:64
	onColorChange ColorPicker.tsx:36
	handleChange ColorPickerPopover.tsx:60
	onColorSelect NamedColorsPalette.tsx:21
	onClick NamedColorsGroup.tsx:109
v12React	unstable_runWithPriority scheduler.production.min.js:18
Hi3React angular.js:14800:15
a3Angular	n ng_react.ts:64
	onColorChange ColorPicker.tsx:36
	handleChange ColorPickerPopover.tsx:60
	onColorSelect NamedColorsPalette.tsx:21
	onClick NamedColorsGroup.tsx:109
v12React	unstable_runWithPriority scheduler.production.min.js:18
Hi3React

**Comment by diafour** [comment]
Thanks for your bug report. Color chooser is fixed in master branch.
